### PR TITLE
Tidied it up a little, and got it working again

### PR DESCRIPTION
**Pull request by voliminal991**
Hi Guys,

Just a really basic update, got things working.

I found that the regex wasn't working as expected, and found we were using the wrong variable within __init__. I've created issues for these, and added them into my commit notes. 

Once this gets approved I'll mark them as completed.

Hopefully it works for you and isn't some horrible cross platform junk! 

David

### CODE REVIEW

**Comment by UndeadScythes** [comment]
Good stuff. That last optional capture group in the regex was lazier than I thought. I'll have to get in there and add the rest if those key mappings soon!

**Comment by UndeadScythes** [comment]
P.S. In your commit's notes you can write "closes issue #X" and GitHub will automatically mark and link the issue when the request gets pulled.

**Comment by UndeadScythes** [comment]
Haha ignore me - just lookes at your full notes!

**Comment by voliminal991** [comment]
Ahh I didn't know that, that's super helpful!

I was thinking of waiting for both of you guys to review and merge
before doing it, but knowing that it automatically does it is amazing!

I wonder what happens if you reference another pull request? Would it
just do nothing, or would the world explode!?

**Pull request merged**
